# Generated by Django 5.0.7 on 2024-07-20 19:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_type", models.CharField(max_length=255)),
                ("mark", models.IntegerField()),
                (
                    "line_datetime",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 7, 20, 22, 59, 26, 621672)
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mental_backend.users",
                    ),
                ),
            ],
        ),
    ]
